source "https://rubygems.org"

ruby "~> 3.3.0"

gem "rails", "~> 7.1.0"
gem "pg", "~> 1.5"
gem "puma", "~> 6.4"
gem "redis", "~> 5.0"
gem "sidekiq", "~> 7.2"

# Authentication & Authorization
gem "devise", "~> 4.9"
gem "devise-jwt", "~> 0.11"
gem "pundit", "~> 2.3"

# API
gem "jbuilder", "~> 2.11"
gem "rack-cors", "~> 2.0"
gem "pagy", "~> 6.2"

# PDF Generation
gem "prawn", "~> 2.4"
gem "prawn-table", "~> 0.2"

# Background Jobs
gem "sidekiq-cron", "~> 1.12"

# Utilities
gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[mri]
  gem "rspec-rails", "~> 6.1"
  gem "factory_bot_rails", "~> 6.4"
  gem "faker", "~> 3.2"
end

group :development do
  gem "annotate", "~> 3.2"
end

group :test do
  gem "shoulda-matchers", "~> 5.3"
  gem "database_cleaner-active_record", "~> 2.1"
end
